#heat_template_version: 2013-05-23
heat_template_version: 2016-04-08

description: Simple template to deploy a single compute instance


parameters:
  stack_name:
    type: string
    label: stack_name 
    description: Name of the stack
    default: basic
  entry_instance_count:
    type: string
    label: entry_instance_count
    description: Number of instance 
    default: 2
  app_instance_count:
    type: string
    label: app_instance_count
    description: Number of instance 
    default: 2
  service_instance_count:
    type: string
    label: entry_instance_count
    description: Number of instance 
    default: 2
  flavor:
    type: string
    label: flavor
    description: Type of instance (flavor) 
    default: 1 GB Performance
  image:
    type: string
    label: image
    description: Type of instance (flavor) 
    default: CentOS 7 (PVHVM)
  ssh_key:
    type: string
    label: ssh_key
    description: The ssh key for admin connections
    default: ssh-key
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: PublicNet

resources:
  network:
    type: network.yaml
    properties:
      stack_name: { get_param: stack_name }
      public_network: { get_param: public_network }

  app_instances:
    type: app_instances.yaml
    properties:
      stack_name: { get_param: stack_name }
      instance_count: { get_param: app_instance_count }
      flavor: { get_param: flavor }
      image: { get_param: image }
      ssh_key: { get_param: ssh_key }
      private_network: { get_attr: [network, name] }

  service_instances:
    type: services_instances.yaml
    properties:
      stack_name: { get_param: stack_name }
      instance_count: { get_param: service_instance_count }
      flavor: { get_param: flavor }
      image: { get_param: image }
      ssh_key: { get_param: ssh_key }
      private_network: { get_attr: [network, name] }
