#heat_template_version: 2013-05-23
heat_template_version: 2014-10-16

description: Simple template to deploy a single compute instance


parameters:
  stack_name:
    type: string
    label: stack_name 
    description: Name of the stack
    default: basic
  instance_count:
    type: string
    label: instance_count
    description: Number of instance 
    default: 2
  flavor:
    type: string
    label: flavor
    description: Type of instance (flavor) 
    default: 1 GB Performance
  image:
    type: string
    label: image
    description: Type of instance (flavor) 
    default: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
  ssh_key:
    type: string
    label: ssh_key
    description: The ssh key for admin connections
    default: ssh-key
  private_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: private


resources:
  instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instance_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          # create a unique name for each server
          # using its index in the group
          name: 
            str_replace:
              template: stack%_instance_%index%
              params:
                "stack%": { get_param: stack_name }
          image: { get_param: image }
          flavor: { get_param: flavor }
          key_name: { get_param: ssh_key }
#          security_groups:
#            - { get_resource: admin_security_group }
#            - { get_resource: web_server_security_group }

