#heat_template_version: 2013-05-23
heat_template_version: 2016-04-08

description: Simple template to deploy a single compute instance


parameters:
  stack_name:
    type: string
    label: stack_name 
    description: Name of the stack
    default: basic
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public


resources:
  entry_network:
    type: OS::Neutron::Net

  entry_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: entry_network }
      cidr: 192.168.1.0/23
      dns_nameservers:
        - 8.8.8.8

  app_network:
    type: OS::Neutron::Net

  app_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: app_network }
      cidr: 192.168.20.0/23
      dns_nameservers:
        - 8.8.8.8

  services_network:
    type: OS::Neutron::Net

  services_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: services_network}
      cidr: 192.168.40.0/23
      dns_nameservers:
        - 8.8.8.8

  admin_network:
    type: OS::Neutron::Net

  admin_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: admin_network}
      cidr: 192.168.240.0/23
      dns_nameservers:
        - 8.8.8.8
  
#  router:
#    type: OS::Neutron::Router
#    properties:
#      external_gateway_info:
#        network: { get_param: public_network }

#  router-interface:
#    type: OS::Neutron::RouterInterface
#    properties:
#      router: { get_resource: router }
#      subnet: { get_resource: private_subnet }

outputs:
  name:
    description: The private application network.
    value: { get_attr: [app_network, name] }


    #  admin_security_group:
    #    type: OS::Neutron::SecurityGroup
    #    properties:
    #      name: web_server_security_group
    #      rules:
    #      - protocol: icmp
    #      - protocol: tcp
    #        port_range_min: 22
    #        port_range_max: 22
    #  web_server_security_group:
    #    type: OS::Neutron::SecurityGroup
    #    properties:
    #      name: web_server_security_group
    #      rules:
    #      - protocol: tcp
    #        port_range_min: 443
    #        port_range_max: 443
