#heat_template_version: 2013-05-23
heat_template_version: 2014-10-16

description: Simple template to deploy a single compute instance


parameters:
  stack_name:
    type: string
    label: stack_name 
    description: Name of the stack
    default: basic
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public


resources:
  private_network:
    type: OS::Neutron::Net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      cidr: 192.168.0.0/23
      dns_nameservers:
        - 8.8.8.8

outputs:
  name:
    description: The private network.
    value: { get_attr: [private_network, name] }

#  router:
#    type: OS::Neutron::Router
#    properties:
#      external_gateway_info:
#        network: { get_param: public_network }

#  router-interface:
#    type: OS::Neutron::RouterInterface
#    properties:
#      router_id: { get_resource: router }
#      subnet: { get_resource: private_subnet }

    #  admin_security_group:
    #    type: OS::Neutron::SecurityGroup
    #    properties:
    #      name: web_server_security_group
    #      rules:
    #      - protocol: icmp
    #      - protocol: tcp
    #        port_range_min: 22
    #        port_range_max: 22
    #  web_server_security_group:
    #    type: OS::Neutron::SecurityGroup
    #    properties:
    #      name: web_server_security_group
    #      rules:
    #      - protocol: tcp
    #        port_range_min: 443
    #        port_range_max: 443
